

# [[main]]
#   name = "Home"
#   url = "#about"
#   weight = 10

[[main]]
  name = "Property Casebook"
  url = "/courses/property"
  weight = 20

[[main]]
  name = "About"
  url = "/about"
  weight = 40

